export const GREY = '#F3F5F8'
export const DARK_GREY = '#DDDDDD'
export const BACKGROUND = '#F5F5F5'
export const WHITE = '#FFFfff'
export const PRIMARY = '#3366FF'
export const ORANGE = '#DD5A10'
export const DANGER = '#EE1818'
export const BLACK = '#000000'
